version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    expose:
      - '4200'
    ports:
      - '4200:4200'
    env_file: .env
    volumes:
      - ./../client-integration-layer-backend/cil-lib:/usr/app/node_modules/cil-lib
